name: Release

on:
  release:
    types: [published]

env:
    DEBIAN_FRONTEND: noninteractive
    NODE_VERSION: 20.x
    NPM_TOKEN: ${{ secrets.OWNSTAK_NPM_TOKEN }}
    NPM_REGISTRY: '//registry.npmjs.org'

defaults:
    run:
        shell: bash

jobs:
    release-next:
        name: Build and release
        timeout-minutes: 10
        runs-on: [self-hosted, linux, arm64]
        container:
            image: node:20
        permissions:
            contents: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup cache
              uses: actions/cache@v4
              with:
                  path: |
                      node_modules
                      ~/.npm
                  key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-${{ env.NODE_VERSION }}-

            - name: Configure GIT
              run: |
                  git config --global --add safe.directory $(pwd)
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git config --global user.name "github-actions[bot]"

            - name: Configure NPM authentication
              if: env.NPM_TOKEN != ''
              run: npm set "${{ env.NPM_REGISTRY }}/:_authToken=${{ env.NPM_TOKEN }}"

            - name: Install dependencies
              run: npm install --no-audit

            - name: Set version from release tag
              run: npm version ${GITHUB_REF_NAME#v} --no-git-tag-version # e.g. 1.0.1

            - name: Build
              run: npm run build

            - name: Release
              if: env.NPM_TOKEN != ''
              run: cd ./dist && npm publish --access public --tag=latest

            - name: Bump version
              run: npm run bump-version

            - name: Push the new version to the repository
              run: |
                git config --global --add safe.directory $(pwd)
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git config --global user.name "github-actions[bot]"
                git add package.json
                git commit -m "Bump version" || echo "Nothing to commit"
                git push origin HEAD:main || echo "Nothing to push"