name: MR CI
on:
    pull_request:

# Stop previous runs when new commit is pushed into the MR
concurrency:
    group: release-next-${{ github.ref }}
    cancel-in-progress: true

env:
    DEBIAN_FRONTEND: noninteractive
    NODE_VERSION: 20.x
    NPM_TOKEN: ${{ secrets.OWNSTAK_NPM_TOKEN }}
    NPM_REGISTRY: '//registry.npmjs.org'

defaults:
    run:
        shell: bash

jobs:
    release-next:
        name: Build and release under next tag
        timeout-minutes: 10
        runs-on: [self-hosted, linux, arm64]
        container:
            image: node:20
        permissions:
            contents: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup cache
              uses: actions/cache@v4
              with:
                  path: |
                      node_modules
                      ~/.npm
                  key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-${{ env.NODE_VERSION }}-

            - name: Configure GIT
              run: |
                  git config --global --add safe.directory $(pwd)
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git config --global user.name "github-actions[bot]"

            - name: Configure NPM authentication
              if: env.NPM_TOKEN != ''
              run: npm set "${{ env.NPM_REGISTRY }}/:_authToken=${{ env.NPM_TOKEN }}"

            - name: Install dependencies
              run: npm install --no-audit

            - name: Set next version
              run: |
                  VERSION=$(npm pkg get version | tr -d '"')
                  PR_NUMBER=${{ github.event.pull_request.number }}
                  TIMESTAMP=$(date +%s)
                  npm version "${VERSION}-next-${PR_NUMBER}-${TIMESTAMP}" --no-git-tag-version

            - name: Build
              run: npm run build

            - name: Release Next
              if: env.NPM_TOKEN != ''
              run: cd ./dist && npm publish --access public --tag=next
