name: Release LATEST

on:
    release:
        types: [published]

env:
    DEBIAN_FRONTEND: noninteractive
    NODE_VERSION: 20.x
    NPM_REGISTRY: '//registry.npmjs.org'

permissions:
    id-token: write
    contents: write

defaults:
    run:
        shell: bash

jobs:
    release-latest:
        name: Release LATEST
        timeout-minutes: 10
        runs-on: ubuntu-slim

        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  registry-url: https:${{ env.NPM_REGISTRY }}

            - name: Setup cache
              uses: actions/cache@v4
              with:
                  path: |
                      node_modules
                      ~/.npm
                  key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-${{ env.NODE_VERSION }}-

            - name: Configure GIT
              run: |
                  git config --global --add safe.directory $(pwd)
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git config --global user.name "github-actions[bot]"

            # Ensure npm 11.5.1 or later is installed for OIDC support
            - name: Update npm
              run: npm install -g npm@latest
              
            - name: Install dependencies
              run: npm install --no-audit

            - name: Set version from release tag
              run: npm version ${GITHUB_REF_NAME#v} --no-git-tag-version || echo "No version change" # e.g. 1.0.1

            - name: Build
              run: npm run build

            - name: Release LATEST
              run: cd ./dist && npm publish --provenance --access public --tag=latest

            - name: Bump version
              run: npm run bump-version

            - name: Push the new version to the repository
              run: |
                  git config --global --add safe.directory $(pwd)
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git config --global user.name "github-actions[bot]"
                  git add package.json
                  git commit -m "Bump version" || echo "Nothing to commit"
                  git push origin HEAD:main || echo "Nothing to push"
